apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv0001
spec:
  capacity:
    storage: 25Gi
  accessModes:
  - ReadWriteOnce
  storageClassName: local-storage
  local:
    path: /tmp
  persistentVolumeReclaimPolicy: Recycle